### ISSUE TITLE
Viewing / Editing of all doc type except PDF not possible anymore

### ISSUE THREAD

**Issue by jprusch** [CollaboraOnline/collabora-mattermost#17]
Hi,
this might be am issue with the current Collabra version as the plugin and Mattermost didn't change
* collaboraoffice 6.4.10.6-6
* loolwsd  6.4.0-7
* Mattermost 5.27.0
In Mattermost we only see the view/comment link on PDF files. All other office documents do not display an edit link.
![collabra_mattermost_issue](https://user-images.githubusercontent.com/9337414/95549320-55796500-0a07-11eb-8348-75e3239c85a8.PNG)

Mattermost was restarted, Collabra server  was restarted. The logs do not shown any errors or hints.
`2020-10-08T16:16:35.473+0200    info    go-plugin@v1.3.0/stream.go:15   WOPI address changed. Load new WOPI file info.  {"plugin_id": "com.collaboraonline.mattermost", "source": "plugin_stdout"}
2020-10-08T16:16:35.861+0200    info    go-plugin@v1.3.0/stream.go:15   WOPI file info loaded successfully!     {"plugin_id": "com.collaboraonline.mattermost", "source": "plugin_stdout"}
`
I provide the discovery xml for reference.
[discovery_xml.txt](https://github.com/CollaboraOnline/collabora-mattermost/files/5352830/discovery_xml.txt)
Any ideas?
Best regards
Jan-Peter

**Comment by kendy** [comment]
@jprusch: Hi @jprusch, thank you for the report! We'll try to reproduce & see how can we fix that.

**Comment by jprusch** [comment]
Liebe Kollegen,

ich bin vom 12.10.2020  bis zum 01.11.2020  nicht im Hause und habe daher leider keinen Zugriff auf meine E-Mails.

Die Mail wird NICHT weitergeleitet und nach meiner R++ckkehr bearbeitet.

In dringende F+ñllen wendet Euch bitte an Hr. Tarrach (v.tarrach@schaeferbarthold.de) oder erfasst ein Ticket ++ber

https://connect.schaeferbarthold.de/jira/servicedesk/customer/portal/3


Liebe Gr+++e

Jan-Peter Rusch

TEL +49 (0)571-502-145
j.rusch@schaeferbarthold.de







-á
@jprusch: Hi @jprusch, thank you for the report! We'll try to reproduce & see how can we fix that.

**Comment by jprusch** [comment]
Sehr geehrte Damen und Herren,

ich bin vom 12.10.2020  bis zum 01.11.2020  nicht im Hause und habe daher leider keinen Zugriff auf meine E-Mails.

Ihre Mail wird NICHT weitergeleitet und nach meiner Rückkehr bearbeitet.

In dringende Fällen wenden Sie sich bitte an Hr. Tarrach (v.tarrach@schaeferbarthold.de).

Mit freundlichen Grüßen

i.V. Jan-Peter Rusch

TEL +49 (0)571-502-145
j.rusch@schaeferbarthold.de


______________________________________________________________________


Schäferbarthold GmbH
Erbeweg 2-12 | 32457 Porta Westfalica | Deutschland
www.schaeferbarthold.de




Schäferbarthold GmbH: Amtsgericht Bad Oeynhausen HRB 3748
Geschäftsführer: Dr. Volker Schäferbarthold, Dr. Christian Schäferbarthold, Wolfgang Schäferbarthold




@jprusch: Hi @jprusch, thank you for the report! We'll try to reproduce & see how can we fix that.

**Comment by mikekaganski** [comment]
https://github.com/CollaboraOnline/collabora-mattermost/pull/18 should handle that.

**Comment by jprusch** [comment]
Sehr geehrte Damen und Herren,

ich bin vom 12.10.2020  bis zum 01.11.2020  nicht im Hause und habe daher leider keinen Zugriff auf meine E-Mails.

Ihre Mail wird NICHT weitergeleitet und nach meiner Rückkehr bearbeitet.

In dringende Fällen wenden Sie sich bitte an Hr. Tarrach (v.tarrach@schaeferbarthold.de).

Mit freundlichen Grüßen

i.V. Jan-Peter Rusch

TEL +49 (0)571-502-145
j.rusch@schaeferbarthold.de


______________________________________________________________________


Schäferbarthold GmbH
Erbeweg 2-12 | 32457 Porta Westfalica | Deutschland
www.schaeferbarthold.de




Schäferbarthold GmbH: Amtsgericht Bad Oeynhausen HRB 3748
Geschäftsführer: Dr. Volker Schäferbarthold, Dr. Christian Schäferbarthold, Wolfgang Schäferbarthold




https://github.com/CollaboraOnline/collabora-mattermost/pull/18 should handle that.

**Comment by jprusch** [comment]
Liebe Kollegen,

ich bin vom 12.10.2020  bis zum 01.11.2020  nicht im Hause und habe daher leider keinen Zugriff auf meine E-Mails.

Die Mail wird NICHT weitergeleitet und nach meiner R++ckkehr bearbeitet.

In dringende F+ñllen wendet Euch bitte an Hr. Tarrach (v.tarrach@schaeferbarthold.de) oder erfasst ein Ticket ++ber

https://connect.schaeferbarthold.de/jira/servicedesk/customer/portal/3


Liebe Gr+++e

Jan-Peter Rusch

TEL +49 (0)571-502-145
j.rusch@schaeferbarthold.de







-á
https://github.com/CollaboraOnline/collabora-mattermost/pull/18 should handle that.

**Comment by jprusch** [comment]
Liebe Kollegen,

ich bin vom 12.10.2020  bis zum 01.11.2020  nicht im Hause und habe daher leider keinen Zugriff auf meine E-Mails.

Die Mail wird NICHT weitergeleitet und nach meiner R++ckkehr bearbeitet.

In dringende F+ñllen wendet Euch bitte an Hr. Tarrach (v.tarrach@schaeferbarthold.de) oder erfasst ein Ticket ++ber

https://connect.schaeferbarthold.de/jira/servicedesk/customer/portal/3


Liebe Gr+++e

Jan-Peter Rusch

TEL +49 (0)571-502-145
j.rusch@schaeferbarthold.de







-á
well..

When can we expect a release based on this commit ?
Tried compiling it for 3 hours now, still stuck on npm errors

**Comment by jprusch** [comment]
Sehr geehrte Damen und Herren,

ich bin vom 12.10.2020  bis zum 01.11.2020  nicht im Hause und habe daher leider keinen Zugriff auf meine E-Mails.

Ihre Mail wird NICHT weitergeleitet und nach meiner Rückkehr bearbeitet.

In dringende Fällen wenden Sie sich bitte an Hr. Tarrach (v.tarrach@schaeferbarthold.de).

Mit freundlichen Grüßen

i.V. Jan-Peter Rusch

TEL +49 (0)571-502-145
j.rusch@schaeferbarthold.de


______________________________________________________________________


Schäferbarthold GmbH
Erbeweg 2-12 | 32457 Porta Westfalica | Deutschland
www.schaeferbarthold.de




Schäferbarthold GmbH: Amtsgericht Bad Oeynhausen HRB 3748
Geschäftsführer: Dr. Volker Schäferbarthold, Dr. Christian Schäferbarthold, Wolfgang Schäferbarthold




well..

When can we expect a release based on this commit ?
Tried compiling it for 3 hours now, still stuck on npm errors

**Comment by lordbaco** [comment]
You can try with my patch to compile it
https://github.com/lordbaco/collabora-mattermost/commit/67e28c39b06e98d38166a122a98d6400c01d2646

Or download the version 1.0.1, I did
https://github.com/lordbaco/collabora-mattermost/releases/tag/1.0.1

**Comment by jprusch** [comment]
Liebe Kollegen,

ich bin vom 12.10.2020  bis zum 01.11.2020  nicht im Hause und habe daher leider keinen Zugriff auf meine E-Mails.

Die Mail wird NICHT weitergeleitet und nach meiner R++ckkehr bearbeitet.

In dringende F+ñllen wendet Euch bitte an Hr. Tarrach (v.tarrach@schaeferbarthold.de) oder erfasst ein Ticket ++ber

https://connect.schaeferbarthold.de/jira/servicedesk/customer/portal/3


Liebe Gr+++e

Jan-Peter Rusch

TEL +49 (0)571-502-145
j.rusch@schaeferbarthold.de







-á
You can try with my patch to compile it
https://github.com/lordbaco/collabora-mattermost/commit/67e28c39b06e98d38166a122a98d6400c01d2646

Or download the version 1.0.1, I did
https://github.com/lordbaco/collabora-mattermost/releases/tag/1.0.1

**Comment by jprusch** [comment]
Sehr geehrte Damen und Herren,

ich bin vom 12.10.2020  bis zum 01.11.2020  nicht im Hause und habe daher leider keinen Zugriff auf meine E-Mails.

Ihre Mail wird NICHT weitergeleitet und nach meiner Rückkehr bearbeitet.

In dringende Fällen wenden Sie sich bitte an Hr. Tarrach (v.tarrach@schaeferbarthold.de).

Mit freundlichen Grüßen

i.V. Jan-Peter Rusch

TEL +49 (0)571-502-145
j.rusch@schaeferbarthold.de


______________________________________________________________________


Schäferbarthold GmbH
Erbeweg 2-12 | 32457 Porta Westfalica | Deutschland
www.schaeferbarthold.de




Schäferbarthold GmbH: Amtsgericht Bad Oeynhausen HRB 3748
Geschäftsführer: Dr. Volker Schäferbarthold, Dr. Christian Schäferbarthold, Wolfgang Schäferbarthold




You can try with my patch to compile it
https://github.com/lordbaco/collabora-mattermost/commit/67e28c39b06e98d38166a122a98d6400c01d2646

Or download the version 1.0.1, I did
https://github.com/lordbaco/collabora-mattermost/releases/tag/1.0.1

**Comment by QuentinBibas** [comment]
thanks a bunch, I wasn't able to figure out the steps and versions of things to actually compile it myself in the time I had available, sadly

**Comment by jprusch** [comment]
Liebe Kollegen,

ich bin vom 12.10.2020  bis zum 01.11.2020  nicht im Hause und habe daher leider keinen Zugriff auf meine E-Mails.

Die Mail wird NICHT weitergeleitet und nach meiner R++ckkehr bearbeitet.

In dringende F+ñllen wendet Euch bitte an Hr. Tarrach (v.tarrach@schaeferbarthold.de) oder erfasst ein Ticket ++ber

https://connect.schaeferbarthold.de/jira/servicedesk/customer/portal/3


Liebe Gr+++e

Jan-Peter Rusch

TEL +49 (0)571-502-145
j.rusch@schaeferbarthold.de







-á
thanks a bunch, I wasn't able to figure out the steps and versions of things to actually compile it myself in the time I had available, sadly

**Comment by jprusch** [comment]
Sehr geehrte Damen und Herren,

ich bin vom 12.10.2020  bis zum 01.11.2020  nicht im Hause und habe daher leider keinen Zugriff auf meine E-Mails.

Ihre Mail wird NICHT weitergeleitet und nach meiner Rückkehr bearbeitet.

In dringende Fällen wenden Sie sich bitte an Hr. Tarrach (v.tarrach@schaeferbarthold.de).

Mit freundlichen Grüßen

i.V. Jan-Peter Rusch

TEL +49 (0)571-502-145
j.rusch@schaeferbarthold.de


______________________________________________________________________


Schäferbarthold GmbH
Erbeweg 2-12 | 32457 Porta Westfalica | Deutschland
www.schaeferbarthold.de




Schäferbarthold GmbH: Amtsgericht Bad Oeynhausen HRB 3748
Geschäftsführer: Dr. Volker Schäferbarthold, Dr. Christian Schäferbarthold, Wolfgang Schäferbarthold




thanks a bunch, I wasn't able to figure out the steps and versions of things to actually compile it myself in the time I had available, sadly

**Comment by lordbaco** [comment]
> thanks a bunch, I wasn't able to figure out the steps and versions of things to actually compile it myself in the time I had available, sadly

I used 
```
cat <<'EOT' >> ~/.bashrc
export GOROOT="$HOME/go1.14"
export GOPATH="$HOME/go"
export PATH="$PATH:$GOROOT/bin"
ulimit -n 8096
EOT

curl -sLO https://golang.org/dl/go1.14.linux-amd64.tar.gz
tar -C ~ -xzf go1.14.linux-amd64.tar.gz
mv ~/go ~/go1.14
mkdir ~/go
git clone https://github.com/lordbaco/collabora-mattermost.git
cd collabora-mattermost
sudo apt-get install npm
make
```
On the Docker side:
```
NCDOMAIN=mattermost\\.domain\\.com|nextcloud\\.domain.com
DOMAIN=collabora.domain.com
USERNAME=admin
PASSWORD=whatever...

  collabora:
    image: collabora/code:latest
    hostname: collabora
    restart: unless-stopped
    cap_add:
      - MKNOD
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- ./loolwsd.xml:/etc/loolwsd/loolwsd.xml
    environment:
      domain: '${NCDOMAIN}'
      username: '${USERNAME}'
      password: '${PASSWORD}'
      dictionaries: 'fr_FR en_US'
      extra_params: '--o:ssl.enable=false --o:ssl.termination=true'
      #server_name: 'collabora'
      #DONT_GEN_SSL_CERT: '1'
    expose:
      - '9980'
    networks:
      - wan
    labels:
      traefik.enable: 'true'
      traefik.http.routers.collabora.service: 'collabora'
      traefik.http.routers.collabora.entrypoints: 'https'
      traefik.http.routers.collabora.rule: 'Host(`collabora.${DOMAIN}`)'
      traefik.http.routers.collabora.tls: 'true'
      traefik.http.routers.collabora.tls.certresolver: 'http'
      traefik.http.services.collabora.loadbalancer.passhostheader: 'true'
      traefik.http.services.collabora.loadbalancer.server.port: '9980'
      traefik.docker.network: 'wan'
      com.centurylinklabs.watchtower.enable: 'true'
```

**Comment by jprusch** [comment]
Liebe Kollegen,

ich bin vom 12.10.2020  bis zum 01.11.2020  nicht im Hause und habe daher leider keinen Zugriff auf meine E-Mails.

Die Mail wird NICHT weitergeleitet und nach meiner R++ckkehr bearbeitet.

In dringende F+ñllen wendet Euch bitte an Hr. Tarrach (v.tarrach@schaeferbarthold.de) oder erfasst ein Ticket ++ber

https://connect.schaeferbarthold.de/jira/servicedesk/customer/portal/3


Liebe Gr+++e

Jan-Peter Rusch

TEL +49 (0)571-502-145
j.rusch@schaeferbarthold.de







-á
> thanks a bunch, I wasn't able to figure out the steps and versions of things to actually compile it myself in the time I had available, sadly

I used 
```
cat <<'EOT' >> ~/.bashrc
export GOROOT="$HOME/go1.14"
export GOPATH="$HOME/go"
export PATH="$PATH:$GOROOT/bin"
ulimit -n 8096
EOT

curl -sLO https://golang.org/dl/go1.14.linux-amd64.tar.gz
tar -C ~ -xzf go1.14.linux-amd64.tar.gz
mv ~/go ~/go1.14
mkdir ~/go
git clone https://github.com/lordbaco/collabora-mattermost.git
cd collabora-mattermost
sudo apt-get install npm
make
```
On the Docker side:
```
NCDOMAIN=mattermost\\.domain\\.com|nextcloud\\.domain.com
DOMAIN=collabora.domain.com
USERNAME=admin
PASSWORD=whatever...

  collabora:
    image: collabora/code:latest
    hostname: collabora
    restart: unless-stopped
    cap_add:
      - MKNOD
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- ./loolwsd.xml:/etc/loolwsd/loolwsd.xml
    environment:
      domain: '${NCDOMAIN}'
      username: '${USERNAME}'
      password: '${PASSWORD}'
      dictionaries: 'fr_FR en_US'
      extra_params: '--o:ssl.enable=false --o:ssl.termination=true'
      #server_name: 'collabora'
      #DONT_GEN_SSL_CERT: '1'
    expose:
      - '9980'
    networks:
      - wan
    labels:
      traefik.enable: 'true'
      traefik.http.routers.collabora.service: 'collabora'
      traefik.http.routers.collabora.entrypoints: 'https'
      traefik.http.routers.collabora.rule: 'Host(`collabora.${DOMAIN}`)'
      traefik.http.routers.collabora.tls: 'true'
      traefik.http.routers.collabora.tls.certresolver: 'http'
      traefik.http.services.collabora.loadbalancer.passhostheader: 'true'
      traefik.http.services.collabora.loadbalancer.server.port: '9980'
      traefik.docker.network: 'wan'
      com.centurylinklabs.watchtower.enable: 'true'
```

**Comment by jprusch** [comment]
Sehr geehrte Damen und Herren,

ich bin vom 12.10.2020  bis zum 01.11.2020  nicht im Hause und habe daher leider keinen Zugriff auf meine E-Mails.

Ihre Mail wird NICHT weitergeleitet und nach meiner Rückkehr bearbeitet.

In dringende Fällen wenden Sie sich bitte an Hr. Tarrach (v.tarrach@schaeferbarthold.de).

Mit freundlichen Grüßen

i.V. Jan-Peter Rusch

TEL +49 (0)571-502-145
j.rusch@schaeferbarthold.de


______________________________________________________________________


Schäferbarthold GmbH
Erbeweg 2-12 | 32457 Porta Westfalica | Deutschland
www.schaeferbarthold.de




Schäferbarthold GmbH: Amtsgericht Bad Oeynhausen HRB 3748
Geschäftsführer: Dr. Volker Schäferbarthold, Dr. Christian Schäferbarthold, Wolfgang Schäferbarthold




> thanks a bunch, I wasn't able to figure out the steps and versions of things to actually compile it myself in the time I had available, sadly

I used 
```
cat <<'EOT' >> ~/.bashrc
export GOROOT="$HOME/go1.14"
export GOPATH="$HOME/go"
export PATH="$PATH:$GOROOT/bin"
ulimit -n 8096
EOT

curl -sLO https://golang.org/dl/go1.14.linux-amd64.tar.gz
tar -C ~ -xzf go1.14.linux-amd64.tar.gz
mv ~/go ~/go1.14
mkdir ~/go
git clone https://github.com/lordbaco/collabora-mattermost.git
cd collabora-mattermost
sudo apt-get install npm
make
```
On the Docker side:
```
NCDOMAIN=mattermost\\.domain\\.com|nextcloud\\.domain.com
DOMAIN=collabora.domain.com
USERNAME=admin
PASSWORD=whatever...

  collabora:
    image: collabora/code:latest
    hostname: collabora
    restart: unless-stopped
    cap_add:
      - MKNOD
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- ./loolwsd.xml:/etc/loolwsd/loolwsd.xml
    environment:
      domain: '${NCDOMAIN}'
      username: '${USERNAME}'
      password: '${PASSWORD}'
      dictionaries: 'fr_FR en_US'
      extra_params: '--o:ssl.enable=false --o:ssl.termination=true'
      #server_name: 'collabora'
      #DONT_GEN_SSL_CERT: '1'
    expose:
      - '9980'
    networks:
      - wan
    labels:
      traefik.enable: 'true'
      traefik.http.routers.collabora.service: 'collabora'
      traefik.http.routers.collabora.entrypoints: 'https'
      traefik.http.routers.collabora.rule: 'Host(`collabora.${DOMAIN}`)'
      traefik.http.routers.collabora.tls: 'true'
      traefik.http.routers.collabora.tls.certresolver: 'http'
      traefik.http.services.collabora.loadbalancer.passhostheader: 'true'
      traefik.http.services.collabora.loadbalancer.server.port: '9980'
      traefik.docker.network: 'wan'
      com.centurylinklabs.watchtower.enable: 'true'
```
